spring.application.name=employee-crud-api
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=30064300Amt2p$